version: "3"
services:
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /vol1/1000/docker/nextcloud/mysql:/var/lib/mysql # 自定义
    environment:
      - MYSQL_ROOT_PASSWORD=5f4dcc3b5aa765d61d8327deb882cf99
      - MYSQL_PASSWORD=5f4dcc3b5aa765d61d8327deb882cf99
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud
  nextcloud-redis:
    image: redis:latest
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: always
    networks:
      - nextcloud
  nextcloud-onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    hostname: nextcloud-onlyoffice
    ports:
      - "50001:80"
    restart: always
    environment:
      - JWT_SECRET=5f4dcc3b5aa765d61d8327deb882cf99
    volumes:
      - /vol1/1000/docker/nextcloud/onlyoffice/data:/var/www/onlyoffice/Data # 自定义
      - /vol1/1000/docker/nextcloud/onlyoffice/logs:/var/log/onlyoffice # 自定义
    networks:
      - nextcloud
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    hostname: nextcloud
    restart: always
    ports:
      - 50000:80
    depends_on:
      - nextcloud-db
      - nextcloud-redis
      - nextcloud-onlyoffice
    volumes:
      - /vol1/1000/docker/nextcloud/nextcloud:/var/www/html # 自定义
    environment:
      - MYSQL_PASSWORD=5f4dcc3b5aa765d61d8327deb882cf99
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
    networks:
      - nextcloud
networks:
  nextcloud: